services:
  app:
    build: .
    container_name: cloudshare-md_dev
    user: "${CURRENT_UID}:${CURRENT_GID}"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env_development
    ports:
      - "8080:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app                # Mount current host directory to /app for live code changes
      - /app/node_modules     # Use node_modules from the image, not the host

  db:
    image: postgres:16-alpine
    container_name: postgres-db_dev
    env_file:
      - .env_development
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
