services:
  app:
    # build: .
    image: cloudshare-md-manual-test:latest
    container_name: cloudshare-md_prod
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env_production
    ports:
      - "8080:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    entrypoint: ["./entrypoint.sh"]
    command: ["node", "./src/server.js"]
    mem_limit: 512m
    cpu_shares: 512

  db:
    image: postgres:16-alpine
    container_name: postgres-db_prod
    env_file:
      - .env_production
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres-data:
